### ISSUE TITLE
Offscreen rendering support for MacOS arm64

### ISSUE THREAD

**Issue by GazimSoliev** [chromiumembedded/java-cef#514]
I can't use offscreen rendering on macos with arm64, get an error

**Comment by GazimSoliev** [comment]
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/nd/f4whl9t51blg_xrzkl6nffqc0000gn/T/jogamp_0000/file_cache/jln10734307428632924823/jln17397903611645811074/natives/macosx-universal/libgluegen_rt.dylib: dlopen(/private/var/folders/nd/f4whl9t51blg_xrzkl6nffqc0000gn/T/jogamp_0000/file_cache/jln10734307428632924823/jln17397903611645811074/natives/macosx-universal/libgluegen_rt.dylib, 0x0001): tried: '/private/var/folders/nd/f4whl9t51blg_xrzkl6nffqc0000gn/T/jogamp_0000/file_cache/jln10734307428632924823/jln17397903611645811074/natives/macosx-universal/libgluegen_rt.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/nd/f4whl9t51blg_xrzkl6nffqc0000gn/T/jogamp_0000/file_cache/jln10734307428632924823/jln17397903611645811074/natives/macosx-universal/libgluegen_rt.dylib' (no such file), '/private/var/folders/nd/f4whl9t51blg_xrzkl6nffqc0000gn/T/jogamp_0000/file_cache/jln10734307428632924823/jln17397903611645811074/natives/macosx-universal/li
	at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
	at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
	at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:174)
	at java.base/java.lang.ClassLoader.loadLibrary(ClassLoader.java:2394)
	at java.base/java.lang.Runtime.load0(Runtime.java:755)
	at java.base/java.lang.System.load(System.java:1970)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibraryInternal(JNILibLoaderBase.java:604)
	at com.jogamp.common.jvm.JNILibLoaderBase.access$000(JNILibLoaderBase.java:64)
	at com.jogamp.common.jvm.JNILibLoaderBase$DefaultAction.loadLibrary(JNILibLoaderBase.java:107)
	at com.jogamp.common.jvm.JNILibLoaderBase.loadLibrary(JNILibLoaderBase.java:488)
	at com.jogamp.common.os.DynamicLibraryBundle$GlueJNILibLoader.loadLibrary(DynamicLibraryBundle.java:427)
	at com.jogamp.common.os.Platform$1.run(Platform.java:321)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:318)
	at com.jogamp.common.os.Platform.<clinit>(Platform.java:290)
	at com.jogamp.opengl.GLProfile.<clinit>(GLProfile.java:154)
	at org.cef.browser.CefBrowserOsr.createGLCanvas(CefBrowserOsr.java:146)
	at org.cef.browser.CefBrowserOsr.<init>(CefBrowserOsr.java:104)
	at org.cef.browser.CefBrowserOsr.<init>(CefBrowserOsr.java:95)
	at org.cef.browser.CefBrowserFactory.create(CefBrowserFactory.java:17)
	at org.cef.CefClient.createBrowser(CefClient.java:141)
	at org.cef.CefClient.createBrowser(CefClient.java:134)
	at example.jcef_compose_test.ComposableSingletons$MainKt$lambda$1430197010$1$2.invoke$lambda$1$lambda$0(main.kt:22)
	at androidx.compose.ui.viewinterop.TypedInteropViewHolder.<init>(InteropView.skiko.kt:55)
	at androidx.compose.ui.viewinterop.SwingInteropViewHolder.<init>(SwingInteropViewHolder.desktop.kt:49)
	at androidx.compose.ui.awt.SwingPanel_desktopKt.SwingPanel-euL9pac(SwingPanel.desktop.kt:79)
	at example.jcef_compose_test.ComposableSingletons$MainKt$lambda$1430197010$1$2.invoke(main.kt:20)
	at example.jcef_compose_test.ComposableSingletons$MainKt$lambda$1430197010$1$2.invoke(main.kt:19)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:130)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
	at androidx.compose.ui.awt.ComposeWindow$setContent$5.invoke(ComposeWindow.desktop.kt:157)
	at androidx.compose.ui.awt.ComposeWindow$setContent$5.invoke(ComposeWindow.desktop.kt:156)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
	at androidx.compose.ui.awt.WindowContentLayout_desktopKt.WindowContentLayout(WindowContentLayout.desktop.kt:108)
	at androidx.compose.ui.awt.ComposeWindowPanel$setContent$3$1.invoke(ComposeWindowPanel.desktop.kt:142)
	at androidx.compose.ui.awt.ComposeWindowPanel$setContent$3$1.invoke(ComposeWindowPanel.desktop.kt:141)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:384)
	at androidx.compose.ui.awt.ComposeWindowPanel$setContent$3.invoke(ComposeWindowPanel.desktop.kt:139)
	at androidx.compose.ui.awt.ComposeWindowPanel$setContent$3.invoke(ComposeWindowPanel.desktop.kt:138)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
	at androidx.compose.ui.scene.ComposeContainer$setContent$1$1.invoke(ComposeContainer.desktop.kt:340)
	at androidx.compose.ui.scene.ComposeContainer$setContent$1$1.invoke(ComposeContainer.desktop.kt:339)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:364)
	at androidx.compose.ui.scene.ComposeContainer_desktopKt.ProvideContainerCompositionLocals(ComposeContainer.desktop.kt:532)
	at androidx.compose.ui.scene.ComposeContainer_desktopKt.access$ProvideContainerCompositionLocals(ComposeContainer.desktop.kt:1)
	at androidx.compose.ui.scene.ComposeContainer$setContent$1.invoke(ComposeContainer.desktop.kt:339)
	at androidx.compose.ui.scene.ComposeContainer$setContent$1.invoke(ComposeContainer.desktop.kt:338)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
	at androidx.compose.ui.scene.ComposeSceneMediator$setContent$1$1$1$1.invoke(ComposeSceneMediator.desktop.kt:551)
	at androidx.compose.ui.scene.ComposeSceneMediator$setContent$1$1$1$1.invoke(ComposeSceneMediator.desktop.kt:550)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
	at androidx.compose.ui.layout.OverlayLayout_skikoKt.OverlayLayout(OverlayLayout.skiko.kt:77)
	at androidx.compose.ui.viewinterop.InteropContainer_skikoKt.TrackInteropPlacementContainer(InteropContainer.skiko.kt:138)
	at androidx.compose.ui.viewinterop.SwingInteropContainer$invoke$1.invoke(SwingInteropContainer.desktop.kt:276)
	at androidx.compose.ui.viewinterop.SwingInteropContainer$invoke$1.invoke(SwingInteropContainer.desktop.kt:275)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:384)
	at androidx.compose.ui.viewinterop.SwingInteropContainer.invoke(SwingInteropContainer.desktop.kt:273)
	at androidx.compose.ui.scene.ComposeSceneMediator$setContent$1$1$1.invoke(ComposeSceneMediator.desktop.kt:550)
	at androidx.compose.ui.scene.ComposeSceneMediator$setContent$1$1$1.invoke(ComposeSceneMediator.desktop.kt:549)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:364)
	at androidx.compose.ui.scene.BaseComposeScene$setContent$1$2.invoke(BaseComposeScene.skiko.kt:147)
	at androidx.compose.ui.scene.BaseComposeScene$setContent$1$2.invoke(BaseComposeScene.skiko.kt:146)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:364)
	at androidx.compose.ui.platform.PlatformCompositionLocalsKt.ProvidePlatformCompositionLocals(PlatformCompositionLocals.kt:26)
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2$1$2.invoke(Wrapper.skiko.kt:51)
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2$1$2.invoke(Wrapper.skiko.kt:50)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:364)
	at androidx.compose.ui.platform.CompositionLocalsKt.ProvideCommonCompositionLocals(CompositionLocals.kt:216)
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2$1.invoke(Wrapper.skiko.kt:47)
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2$1.invoke(Wrapper.skiko.kt:46)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:364)
	at androidx.compose.runtime.CompositionLocalKt.CompositionLocalProvider(CompositionLocal.kt:401)
	at androidx.compose.ui.platform.Wrapper_skikoKt.provide(Wrapper.skiko.kt:63)
	at androidx.compose.ui.platform.Wrapper_skikoKt.access$provide(Wrapper.skiko.kt:1)
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2.invoke(Wrapper.skiko.kt:46)
	at androidx.compose.ui.platform.Wrapper_skikoKt$setContent$2.invoke(Wrapper.skiko.kt:45)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:121)
	at androidx.compose.runtime.internal.ComposableLambdaImpl.invoke(ComposableLambda.kt:51)
	at androidx.compose.runtime.internal.Utils_jvmKt.invokeComposable(Utils.jvm.kt:27)
	at androidx.compose.runtime.ComposerImpl.doCompose-aFTiNEg(Composer.kt:3694)
	at androidx.compose.runtime.ComposerImpl.composeContent--ZbOJvo$runtime(Composer.kt:3616)
	at androidx.compose.runtime.CompositionImpl.composeContent(Composition.kt:792)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1137)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:677)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:616)
	at androidx.compose.ui.platform.Wrapper_skikoKt.setContent(Wrapper.skiko.kt:45)
	at androidx.compose.ui.scene.CanvasLayersComposeSceneImpl.createComposition(CanvasLayersComposeScene.skiko.kt:208)
	at androidx.compose.ui.scene.BaseComposeScene.setContent(BaseComposeScene.skiko.kt:146)
	at androidx.compose.ui.scene.ComposeSceneMediator.setContent$lambda$12(ComposeSceneMediator.desktop.kt:549)
	at androidx.compose.ui.scene.ComposeSceneMediator.onComponentAttached(ComposeSceneMediator.desktop.kt:519)
	at androidx.compose.ui.scene.ComposeContainer.addNotify(ComposeContainer.desktop.kt:278)
	at androidx.compose.ui.awt.ComposeWindowPanel.addNotify(ComposeWindowPanel.desktop.kt:119)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/javax.swing.JComponent.addNotify(JComponent.java:4839)
	at java.desktop/javax.swing.JRootPane.addNotify(JRootPane.java:721)
	at java.desktop/java.awt.Container.addNotify(Container.java:2804)
	at java.desktop/java.awt.Window.addNotify(Window.java:791)
	at java.desktop/java.awt.Frame.addNotify(Frame.java:495)
	at java.desktop/java.awt.Window.pack(Window.java:829)
	at androidx.compose.ui.util.Windows_desktopKt.setSizeImpl-6HolHcs(Windows.desktop.kt:115)
	at androidx.compose.ui.util.Windows_desktopKt.setSizeSafely-hQcJfNw(Windows.desktop.kt:54)
	at androidx.compose.ui.window.Window_desktopKt.Window$lambda$23$lambda$22(Window.desktop.kt:240)
	at androidx.compose.ui.window.Window_desktopKt.Window$lambda$40$lambda$39(Window.desktop.kt:621)
	at androidx.compose.ui.window.AwtWindow_desktopKt.AwtWindow$lambda$7$lambda$6(AwtWindow.desktop.kt:78)
	at androidx.compose.ui.util.UpdateEffect_desktopKt.UpdateEffect$lambda$8$lambda$7$performUpdate$lambda$4(UpdateEffect.desktop.kt:59)
	at androidx.compose.runtime.snapshots.Snapshot$Companion.observe(Snapshot.kt:2496)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver$ObservedScopeMap.observe(SnapshotStateObserver.kt:460)
	at androidx.compose.runtime.snapshots.SnapshotStateObserver.observeReads(SnapshotStateObserver.kt:244)
	at androidx.compose.ui.util.UpdateEffect_desktopKt.UpdateEffect$lambda$8$lambda$7$performUpdate(UpdateEffect.desktop.kt:55)
	at androidx.compose.ui.util.UpdateEffect_desktopKt.UpdateEffect$lambda$8$lambda$7(UpdateEffect.desktop.kt:64)
	at androidx.compose.runtime.DisposableEffectImpl.onRemembered(Effects.kt:83)
	at androidx.compose.runtime.internal.RememberEventDispatcher.dispatchRememberList(RememberEventDispatcher.kt:182)
	at androidx.compose.runtime.internal.RememberEventDispatcher.dispatchRememberObservers(RememberEventDispatcher.kt:174)
	at androidx.compose.runtime.CompositionImpl.applyChangesInLocked(Composition.kt:1044)
	at androidx.compose.runtime.CompositionImpl.applyChanges(Composition.kt:1067)
	at androidx.compose.runtime.Recomposer.composeInitial$runtime(Recomposer.kt:1164)
	at androidx.compose.runtime.CompositionImpl.composeInitial(Composition.kt:677)
	at androidx.compose.runtime.CompositionImpl.setContent(Composition.kt:616)
	at androidx.compose.ui.window.Application_desktopKt$awaitApplication$2$1$2.invokeSuspend(Application.desktop.kt:221)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:318)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:773)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:86)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by magreenblatt** [comment]
The jogamp binaries should be universal. Might be something wrong there.

**Comment by KlemenDEV** [comment]
Any updates on this?

**Comment by magreenblatt** [comment]
Updating the binaries to the newest available version could be a good place to start.

**Comment by KlemenDEV** [comment]
Any guidelines on how to do that (where to look at) or how to help with doing that?

**Comment by magreenblatt** [comment]
See https://bitbucket.org/chromiumembedded/java-cef/src/master/third_party/jogamp/README.jcef

Test first if it works for you locally.

**Comment by FriwiDev** [comment]
See https://github.com/jcefmaven/jcefmaven/issues/121 - this is now resolved in jcefmaven by updating the included jogl jar to the main release of jogl 2.4.0 instead of an rc build.

**Comment by magreenblatt** [comment]
@FriwiDev I updated JOGL to 2.4.0, included your fix from #520, and fixed some other related build issues for MacOS 15.7.3 + Xcode 16.4 + OpenJDK 25.0.2, but jcef_app is still crashing for me with `--off-screen-rendering-enabled`.

## The Problem
JCEF with `--off-screen-rendering-enabled` crashes on macOS with "Must only be used from the main thread" in JOGL's `DestroyNSWindow0`.

## Likely Cause
**CEF and JOGL both need the macOS main thread and can't share it.**

- CEF owns the main thread for its browser loop
- Java's `main()` runs on a separate thread
- JOGL needs the main thread for NSWindow operations
- JOGL's `RunOnMainThread` dispatch doesn't work because CEF doesn't pump JOGL's message queue

## What Was Tried

| Attempt | Why It Failed |
|---------|---------------|
| Wrap `removeNotify()` with `OSXUtil.RunOnMainThread` | Crash happens in JOGL's internal init, not our code |
| Set `GLCapabilities.setOnscreen(false)` | JOGL still creates NSWindow during init |
| Skip `removeNotify` on macOS | Doesn't address init crash |
| Pre-init JOGL before CEF starts | Java main thread ≠ macOS main thread |
| Use `-XstartOnFirstThread` | Deadlocks - CEF also needs main thread |

**Comment by magreenblatt** [comment]
It appears that JOGL 2.4.0 has a bug where DestroyNSWindow isn't dispatched to the main thread. This doesn't appear to be fixed even in master.

## Root Cause Chain

1. **JCEF creates a `CefBrowserOsr`** which uses JOGL's `GLCanvas` for hardware-accelerated rendering

2. **JOGL initialization** (`GLProfile.getMaxFixedFunc()`) triggers `MacOSXCGLDrawableFactory.getOrCreateSharedResourceImpl()` which creates a temporary NSWindow for OpenGL capability detection

3. **JOGL spawns `SharedResourceRunner` thread** (not the main thread) to do this work

4. **When cleanup happens**, `DestroyNSWindow0` is called, which executes `[mWin close]` on the SharedResourceRunner thread

5. **macOS requires NSWindow operations on thread 0** (the main thread). Calling `[mWin close]` on any other thread triggers a crash.

## Why JOGL's Fix Doesn't Work

JOGL 2.4.0 added `RunOnMainThread` wrapping for some operations (like `CreateNSWindow`), but **`DestroyNSWindow` is NOT wrapped** - even in master. The native code just calls `[mWin close]` directly on whatever thread invokes it.

## Why Our Attempts Failed

| Attempt | Why It Failed |
|---------|---------------|
| Pre-init JOGL before CEF | Java's `main()` runs on thread 3, not macOS main thread (thread 0) |
| `SwingUtilities.invokeAndWait` | EDT is not the macOS main thread when CEF is running |
| Added `CefMainThreadUtil.runOnMainThread` (PR [here](https://github.com/chromiumembedded/java-cef/pull/525)) | Dispatches the initial call to thread 0, but JOGL's internal `SharedResourceRunner` still spawns separately and calls `DestroyNSWindow` on a different thread |

## The Fundamental Issue

JOGL's internal threading model (SharedResourceRunner) calls `DestroyNSWindow0` on a non-main thread, and there's no way to intercept or redirect this from outside JOGL. The fix must be inside JOGL itself.

**Comment by magreenblatt** [comment]
There doesn't appear to be a publicly editable (submittable) issue tracker for jogamp. Submitting a PR to https://github.com/sgothel/jogl might be the best/only option. We can probably just patch and build it ourselves since we're committing artifacts.

**Comment by magreenblatt** [comment]
Here's the proposed fix (I have not tested it yet).

## Building JOGL 2.4.0 on macOS

### Dependencies

| Tool | Version |
|------|---------|
| JDK | 17+ (Temurin/Adoptium recommended) |
| Ant | 1.8+ |
| Git | 1.6+ |
| Xcode | Command line tools (for clang/gcc) |

### Build Steps

```bash
# 1. Clone both repos (must be side-by-side)
git clone --recurse-submodules https://github.com/sgothel/gluegen.git
git clone --recurse-submodules https://github.com/sgothel/jogl.git

# 2. Checkout 2.4.0 tag
cd gluegen && git checkout v2.4.0 && cd ..
cd jogl && git checkout v2.4.0 && cd ..

# 3. Build gluegen first
cd gluegen/make
ant clean
ant

# 4. Build jogl
cd ../../jogl/make
ant clean
ant
```

### Output JARs

After build, the JARs you need are in:
- `jogl/build/jar/jogl-all.jar`
- `jogl/build/jar/jogl-all-natives-macosx-universal.jar`

### Before Building

1. Delete any ANTLR jars from `/Library/Java/Extensions` (causes conflicts)
2. Ensure `JAVA_HOME` points to JDK 17+
3. Unset `CLASSPATH` if set

## The Fix

Edit `jogl/src/nativewindow/classes/jogamp/nativewindow/macosx/OSXUtil.java`:

```java
// Change this:
public static void DestroyNSWindow(final long nsWindow) {
    DestroyNSWindow0(nsWindow);
}

// To this:
public static void DestroyNSWindow(final long nsWindow) {
    if( IsMainThread() ) {
        DestroyNSWindow0(nsWindow);
    } else {
        RunOnMainThread(true, false, new Runnable() {
            @Override
            public void run() {
                DestroyNSWindow0(nsWindow);
            }
        });
    }
}
```

Then rebuild jogl.

**Comment by KlemenDEV** [comment]
Maybe a way forward for OSR would be to use a non-JOGL approach, something like e.g. IDEA does: https://github.com/JetBrains/intellij-community/blob/idea/252.25557.131/platform/ui.jcef/jcef/JBCefOsrHandler.java (probably a topic for a new ticket, though)

**Comment by magreenblatt** [comment]
> Edit jogl/src/nativewindow/classes/jogamp/nativewindow/macosx/OSXUtil.java

The fix works. Applied to the original 2.4.0 jogl-all.jar file with [patch_jogl.sh](https://github.com/user-attachments/files/24974796/patch_jogl.sh).

Upstream PR fix: https://github.com/sgothel/jogl/pull/119

**Comment by magreenblatt** [comment]
> Maybe a way forward for OSR would be to use a non-JOGL approach, something like e.g. IDEA does:

Looks like they're using Java2D. That's definitely a good/stable option, but potentially slower because it doesn't support GPU-accelerated OpenGL or Metal. Unfortunately there appear to be no good options for Mac if you also want the accelerated performance.

## The Challenge

- Apple deprecated OpenGL
- JavaFX moved to Metal (`-Dprism.order=mtl`)
- CEF's shared texture (PR #524) provides IOSurface/Metal handles
- JavaFX has no public API for importing external textures/IOSurfaces

## Options

| Option | Pros | Cons |
|--------|------|------|
| **JOGL (current)** | GPU accelerated, existing code | macOS threading issues, OpenGL deprecated |
| **Java2D (JetBrains)** | Simple, stable, proven | CPU copy, slower |
| **DriftFX** | Direct Prism integration | Uses internal APIs, fragile |
| **OpenGLFX** | Maintained, works | Designed for OpenGL, not Metal/IOSurface |
| **Custom JNI** | Full control | Complex, must track JavaFX internals |

## Recommendation

For **stability**: Java2D approach (JetBrains style) - copy ByteBuffer to BufferedImage.

For **performance**: DriftFX-style integration with JavaFX's Metal internals, but fragile.

**Comment by magreenblatt** [comment]
I'm still seeing an occasional issue where the jcef_app window appears but does not display the OSR browser content. This suggests at least one remaining unresolved timing problem.

**Comment by magreenblatt** [comment]
It's possible that the JavaAppLauncher threading design is fundamentally flawed. See related discussion at https://github.com/chromiumembedded/java-cef/issues/443#issuecomment-3828946119

**Comment by sgothel** [comment]
> > Edit jogl/src/nativewindow/classes/jogamp/nativewindow/macosx/OSXUtil.java
> 
> The fix works. Applied to the original 2.4.0 jogl-all.jar file with [patch_jogl.sh](https://github.com/user-attachments/files/24974796/patch_jogl.sh).
> 
> Upstream PR fix: [sgothel/jogl#119](https://github.com/sgothel/jogl/pull/119)

Thank you, will get my hands on it this week. Mentioned a just completed related work in your merge request.

**Comment by sgothel** [comment]
I just like to add that the above exception https://github.com/chromiumembedded/java-cef/issues/514#issuecomment-3218371715 shows the operation is 
- running from the main thread
- you have not produced a fat universal native lib (like our JogAmp build for amd64 and arm64)

The commit for JOGL seems to be a nop, see https://github.com/sgothel/jogl/pull/119#issuecomment-3887632263

If I can help, please go ahead ..
A new build shall come soon (currently our latest JogAmp is v2.6.0)

```
Exception in thread "main" java.lang.UnsatisfiedLinkError: /private/var/folders/nd/f4whl9t51blg_xrzkl6nffqc0000gn/T/jogamp_0000/file_cache/jln10734307428632924823/jln17397903611645811074/natives/macosx-universal/libgluegen_rt.dylib: dlopen(/private/var/folders/nd/f4whl9t51blg_xrzkl6nffqc0000gn/T/jogamp_0000/file_cache/jln10734307428632924823/jln17397903611645811074/natives/macosx-universal/libgluegen_rt.dylib, 0x0001): tried: '/private/var/folders/nd/f4whl9t51blg_xrzkl6nffqc0000gn/T/jogamp_0000/file_cache/jln10734307428632924823/jln17397903611645811074/natives/macosx-universal/libgluegen_rt.dylib' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e' or 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/private/var/folders/nd/f4whl9t51blg_xrzkl6nffqc0000gn/T/jogamp_0000/file_cache/jln10734307428632924823/jln17397903611645811074/natives/macosx-universal/libgluegen_rt.dylib' (no such file), '/private/var/folders/nd/f4whl9t51blg_xrzkl6nffqc0000gn/T/jogamp_0000/file_cache/jln10734307428632924823/jln17397903611645811074/natives/macosx-universal/li
at java.base/jdk.internal.loader.NativeLibraries.load(Native Method)
at java.base/jdk.internal.loader.NativeLibraries$NativeLibraryImpl.open(NativeLibraries.java:388)
at java.base/jdk.internal.loader.NativeLibraries.loadLibrary(NativeLibraries.java:232)
```

**Comment by magreenblatt** [comment]
@sgothel Thanks for the follow-up. The call stack from the original issue report is not what we were seeing when testing with OpenJDK 25.0.2 and JOGL 2.4.0. You can follow what we saw while debugging in [this comment](https://github.com/chromiumembedded/java-cef/issues/514#issuecomment-3825455061). Its possible that the issue in already fixed in newer JOGL versions (or different OpenJDK versions) as we were not specifically testing different versions.

**Comment by sgothel** [comment]
> [@sgothel](https://github.com/sgothel) Thanks for the follow-up. The call stack from the original issue report is not what we were seeing when testing with OpenJDK 25.0.2 and JOGL 2.4.0. You can follow what we saw while debugging in [this comment](https://github.com/chromiumembedded/java-cef/issues/514#issuecomment-3825455061). Its possible that the issue in already fixed in newer JOGL versions (or different OpenJDK versions) as we were not specifically testing different versions.

AH, thx. Yes, after 2.4.0 I have fixed these issues for 2.6.0 already. Makes sense. I guess you/I can close this issue then?
See my remarks in your PR.
